---
- name: Docker initialize
  apt: name={{item}} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
  tags: [package, docker]

- name: Add apt-key for docker repositories
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  tags: [package, docker]

- name: Add docker repositories
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present 
  tags: [package, docker]

- name: Install docker prerequisites
  apt: name={{item}} state=latest
  with_items:
    - apparmor
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
  tags: [package, docker]

- name: Install docker engine
  apt: name=docker-engine state=latest
  tags: [package, docker]

- name: Set docker daemon options
  copy: content="DOCKER_OPTS=\"{{ docker_opts.rstrip('\n') }}\"" dest=/etc/default/docker owner=root group=root mode=0644
  notify:
    - Restart docker
  tags: [config, docker]
